using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BackWave.SourceGenerators;

/// <summary>
/// Renders the generated source. Every shape here is exactly what a user would write by
/// hand: straight-line Utf8JsonWriter/Reader code (unknown JSON properties skipped, missing
/// ones defaulted — the tolerant-decode contract), a primary-constructor handler for method
/// sugar, and object-initializer JobRegistrations.
/// </summary>
internal static class JobEmitter
{
    private const string Header = """
        // <auto-generated/>
        // Generated by BackWave.SourceGenerators — exactly what you would write by hand.
        #nullable enable

        """;

    public static string EmitRegistry(
        IReadOnlyList<JobModel> jobs, IReadOnlyList<(string TypeFqn, string ContextFqn)> seedCodecs)
    {
        var source = new StringBuilder(Header);
        source.Append("""
            namespace BackWave.Generated
            {
                /// <summary>The generated Job Registry: every [Job] declaration in this assembly.</summary>
                public static class BackWaveJobs
                {
                    /// <summary>One registration per [Job], ordered by Wire Name.</summary>
                    public static global::System.Collections.Generic.IReadOnlyList<global::BackWave.Jobs.JobRegistration> CreateRegistrations()
                        => new global::BackWave.Jobs.JobRegistration[]
                        {

            """);
        foreach (var job in jobs)
        {
            source.Append($$"""
                            new global::BackWave.Jobs.JobRegistration
                            {
                                WireName = {{Literal(job.WireName)}},
                                JobType = typeof({{job.JobTypeFqn}}),
                                Queue = {{Literal(job.Queue)}},
                                DefaultTags = {{DefaultTags(job)}},

            """);
            if (job.OutputContextFqn is { } outputContextFqn)
            {
                // The step's Job Output codec, referencing the consumer's own JsonSerializerContext - no
                // caller ever passes outputTypeInfo. GetTypeInfo returns the non-generic base, which is
                // exactly the type OutputTypeInfo holds.
                source.Append($$"""
                                    OutputTypeInfo = {{outputContextFqn}}.Default.GetTypeInfo(typeof({{job.OutputTypeFqn}})),

                """);
            }
            source.Append($$"""
                                Serialize = static job => {{WireClassFqn(job)}}.Serialize(({{job.JobTypeFqn}})job),
                                Deserialize = static payload => {{WireClassFqn(job)}}.Deserialize(payload),
                                Execute = static (services, job, context, cancellationToken) =>
                                    (services.GetService(typeof(global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}>)) is global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}> handler
                                        ? handler
                                        : throw new global::System.InvalidOperationException(
                                            "No IJobHandler<{{job.JobTypeName}}> is registered for wire name '{{job.WireName}}'."))
                                    .HandleAsync(({{job.JobTypeFqn}})job, context, cancellationToken),
                            },

            """);
        }
        // Close the registrations array with a trailing blank line before the next member. The blank is
        // written explicitly: a raw string's final blank line collapses, and EmitSeedCodecs may sit here.
        source.Append("            };\n\n");
        EmitSeedCodecs(source, seedCodecs);
        source.Append($$"""
                    /// <summary>The registry over <see cref="CreateRegistrations"/>.</summary>
                    public static global::BackWave.Jobs.JobRegistry CreateRegistry()
                        => new global::BackWave.Jobs.JobRegistry(CreateRegistrations(){{(seedCodecs.Count > 0 ? ", CreateSeedCodecs()" : "")}});

                    /// <summary>
                    /// The DI-free module: the registrations, one (IJobHandler&lt;T&gt;, THandler) handler
                    /// mapping per [Job], and the classes that declare method-sugar [Job]s — all ordered by
                    /// Wire Name. Pass to UseJobs to register the registry, every handler (scoped), and every
                    /// declaring class (scoped) in one call.
                    /// </summary>
                    public static global::BackWave.Jobs.JobModule Module
                        => new global::BackWave.Jobs.JobModule
                        {
                            Registrations = CreateRegistrations(),

            """);
        if (seedCodecs.Count > 0)
        {
            source.Append("""
                            SeedCodecs = CreateSeedCodecs(),

            """);
        }
        source.Append("""
                            Handlers = new global::BackWave.Jobs.JobHandlerMapping[]
                            {

            """);
        foreach (var job in jobs)
        {
            source.Append($$"""
                                new global::BackWave.Jobs.JobHandlerMapping(typeof(global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}>), typeof({{job.HandlerTypeFqn}})),

            """);
        }
        source.Append("""
                            },
                            ContainingTypes = new global::BackWave.Jobs.JobContainingType[]
                            {

            """);
        // The declaring classes of NON-static method-sugar jobs: the generated …Handler ctor-injects
        // one and forwards to it, so it is the job's DI entry. Static-method sugar calls statically
        // (no instance) and class-based handlers are already in Handlers — neither contributes one.
        // Distinct + ordered so the list is stable; the array stays empty when there are none.
        var containingTypes = jobs
            .Where(job => job.Sugar is { IsStatic: false })
            .Select(job => job.Sugar!.ContainingTypeFqn)
            .Distinct()
            .OrderBy(fqn => fqn, System.StringComparer.Ordinal);
        foreach (var containingType in containingTypes)
        {
            source.Append($$"""
                                typeof({{containingType}}),

            """);
        }
        source.Append("""
                            },
                        };
                }
            }

            """);
        return source.ToString();
    }

    /// <summary>
    /// The Workflow Input seed codec map, keyed by seed type - one entry per seed, each referencing the
    /// consumer's own JsonSerializerContext, so a started workflow reads and writes its seed with no
    /// caller-passed serializer. Emitted only when at least one seed is declared; otherwise nothing is
    /// written and the registry/module carry no seed map (older-shaped, source-compatible).
    /// </summary>
    private static void EmitSeedCodecs(
        StringBuilder source, IReadOnlyList<(string TypeFqn, string ContextFqn)> seedCodecs)
    {
        if (seedCodecs.Count == 0)
        {
            return;
        }
        source.Append("""
                    /// <summary>The Workflow Input seed codecs, keyed by seed type - one per declared seed.</summary>
                    public static global::System.Collections.Generic.IReadOnlyDictionary<global::System.Type, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo> CreateSeedCodecs()
                        => new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo>
                        {

            """);
        foreach (var (typeFqn, contextFqn) in seedCodecs)
        {
            source.Append($$"""
                            [typeof({{typeFqn}})] = {{contextFqn}}.Default.GetTypeInfo(typeof({{typeFqn}}))!,

            """);
        }
        // Close the dictionary initializer; explicit trailing blank line separates this method from the
        // CreateRegistry summary that follows (a raw string's final blank line would collapse).
        source.Append("                        };\n\n");
    }

    public static string EmitJob(JobModel job)
    {
        var source = new StringBuilder(Header);
        var hasNamespace = job.Namespace.Length > 0;
        if (hasNamespace)
        {
            source.Append($"namespace {job.Namespace}\n{{\n");
        }

        if (job.Sugar is { } sugar)
        {
            EmitSugarRecord(source, job, sugar);
            EmitSugarHandler(source, job, sugar);
        }
        EmitWireClass(source, job);

        if (hasNamespace)
        {
            source.Append("}\n");
        }
        return source.ToString();
    }

    private static void EmitSugarRecord(StringBuilder source, JobModel job, MethodSugar sugar)
    {
        var parameters = string.Join(", ", job.Members
            .OrderBy(m => m.CtorPosition)
            .Select(m => $"{m.TypeFqn} {m.Name}"));
        source.Append($$"""
                /// <summary>Generated payload for [Job] "{{job.WireName}}".</summary>
                {{sugar.Accessibility}} sealed record {{job.JobTypeName}}({{parameters}});


            """);
    }

    private static void EmitSugarHandler(StringBuilder source, JobModel job, MethodSugar sugar)
    {
        var arguments = string.Join(", ", sugar.CallArguments
            .Select(a => a is "context" or "cancellationToken" ? a : $"job.{a}"));
        var call = sugar.IsStatic
            ? $"{sugar.ContainingTypeFqn}.{sugar.MethodName}({arguments})"
            : $"target.{sugar.MethodName}({arguments})";
        var declaration = sugar.IsStatic
            ? $"{sugar.Accessibility} sealed class {job.JobTypeName}Handler"
            : $"{sugar.Accessibility} sealed class {job.JobTypeName}Handler({sugar.ContainingTypeFqn} target)";
        source.Append($$"""
                /// <summary>Generated handler for [Job] "{{job.WireName}}".</summary>
                {{declaration}} : global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}>
                {
                    public global::System.Threading.Tasks.Task HandleAsync(
                        {{job.JobTypeFqn}} job,
                        global::BackWave.Jobs.JobContext context,
                        global::System.Threading.CancellationToken cancellationToken)
                        => {{call}};
                }


            """);
    }

    private static void EmitWireClass(StringBuilder source, JobModel job)
    {
        source.Append($$"""
                /// <summary>Generated wire format for [Job] "{{job.WireName}}".</summary>
                internal static class {{job.JobTypeName}}Wire
                {
                    public static byte[] Serialize({{job.JobTypeFqn}} value)
                    {
                        var buffer = new global::System.IO.MemoryStream();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(buffer))
                        {
                            writer.WriteStartObject();

            """);
        foreach (var member in job.Members)
        {
            EmitWrite(source, member);
        }
        source.Append($$"""
                            writer.WriteEndObject();
                        }
                        return buffer.ToArray();
                    }

                    public static {{job.JobTypeFqn}} Deserialize(global::System.ReadOnlyMemory<byte> payload)
                    {
                        var reader = new global::System.Text.Json.Utf8JsonReader(payload.Span);

            """);
        foreach (var member in job.Members)
        {
            source.Append($"            {member.LocalTypeFqn()} {member.Local()} = {member.MissingLiteral};\n");
        }
        source.Append("""

                        if (!reader.Read() || reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)
                        {
                            throw new global::System.Text.Json.JsonException("Expected a JSON object.");
                        }
                        while (reader.Read() && reader.TokenType == global::System.Text.Json.JsonTokenType.PropertyName)
                        {

            """);
        var first = true;
        foreach (var member in job.Members)
        {
            EmitRead(source, member, first);
            first = false;
        }

        // Skip unknown / unmodeled properties. With at least one member this is the trailing `else`
        // of the property if/else-if chain; with no members (a job whose payload carries no data)
        // every property is unknown, so the skip is unconditional — an `else` with no preceding `if`
        // would not compile.
        source.Append(job.Members.Count == 0
            ? """
                            reader.Read();
                            reader.Skip();
                        }

            """
            : """
                            else
                            {
                                reader.Read();
                                reader.Skip();
                            }
                        }

            """);

        var ctorArguments = string.Join(", ", job.Members
            .Where(m => m.CtorPosition >= 0)
            .OrderBy(m => m.CtorPosition)
            .Select(m => m.Kind == MemberKind.String && !m.IsNullableValue ? $"{m.Local()}!" : m.Local()));
        var initProps = job.Members.Where(m => m.CtorPosition < 0).ToList();
        var initializer = initProps.Count == 0
            ? ""
            : " { " + string.Join(", ", initProps.Select(m =>
                $"{m.Name} = {(m.Kind == MemberKind.String ? m.Local() + "!" : m.Local())}")) + " }";
        source.Append($$"""
                        return new {{job.JobTypeFqn}}({{ctorArguments}}){{initializer}};
                    }
                }

            """);
    }

    private static void EmitWrite(StringBuilder source, PayloadMember member)
    {
        var name = Literal(member.Name);
        var value = $"value.{member.Name}";
        if (member.IsNullableValue)
        {
            source.Append($$"""
                            if ({{value}}.HasValue)
                            {
                                {{WriteCall(member.Kind, name, value + ".Value")}};
                            }
                            else
                            {
                                writer.WriteNull({{name}});
                            }

            """);
            return;
        }
        if (member.Kind == MemberKind.String)
        {
            source.Append($$"""
                            if ({{value}} is null)
                            {
                                writer.WriteNull({{name}});
                            }
                            else
                            {
                                writer.WriteString({{name}}, {{value}});
                            }

            """);
            return;
        }
        source.Append($"                {WriteCall(member.Kind, name, value)};\n");
    }

    private static string WriteCall(MemberKind kind, string name, string value)
        => kind switch
        {
            MemberKind.Boolean => $"writer.WriteBoolean({name}, {value})",
            MemberKind.Number => $"writer.WriteNumber({name}, {value})",
            MemberKind.Enum => $"writer.WriteString({name}, {value}.ToString())",
            _ => $"writer.WriteString({name}, {value})", // string, Guid, DateTime, DateTimeOffset
        };

    private static void EmitRead(StringBuilder source, PayloadMember member, bool first)
    {
        var keyword = first ? "if" : "else if";
        var local = member.Local();
        string assignment;
        if (member.Kind == MemberKind.Enum)
        {
            var enumType = member.IsNullableValue ? member.TypeFqn.TrimEnd('?') : member.TypeFqn;
            // Strict decode: match the numeric/Guid/DateTime paths and throw on an
            // unparseable token instead of silently defaulting (e.g. a renamed enum
            // member across versions would otherwise become default(TEnum) with no signal).
            // A nullable enum still accepts a JSON null (the writer emits one for HasValue == false).
            var strict = $$"""
                                    if (reader.TokenType == global::System.Text.Json.JsonTokenType.String
                                        && global::System.Enum.TryParse<{{enumType}}>(reader.GetString(), out var {{local}}Parsed))
                                    {
                                        {{local}} = {{local}}Parsed;
                                    }
                                    else
                                    {
                                        throw new global::System.Text.Json.JsonException("Could not decode property '{{member.Name}}' as enum '{{enumType}}'.");
                                    }
                """;
            assignment = member.IsNullableValue
                ? $$"""
                                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                                    {
                                    {{strict}}
                                    }
                """
                : strict;
        }
        else if (member.Kind == MemberKind.String)
        {
            assignment = $$"""
                                    {{local}} = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : reader.GetString();
                """;
        }
        else
        {
            var read = $"reader.{ReadCall(member)}()";
            assignment = member.IsNullableValue
                ? $$"""
                                    {{local}} = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : {{read}};
                """
                : $$"""
                                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                                    {
                                        {{local}} = {{read}};
                                    }
                """;
        }
        source.Append($$"""
                            {{keyword}} (reader.ValueTextEquals({{Literal(member.Name)}}))
                            {
                                reader.Read();
            {{assignment}}
                            }

            """);
    }

    private static string ReadCall(PayloadMember member)
    {
        if (member.Kind == MemberKind.Boolean)
        {
            return "GetBoolean";
        }
        if (member.Kind == MemberKind.Guid)
        {
            return "GetGuid";
        }
        if (member.Kind == MemberKind.DateTime)
        {
            return "GetDateTime";
        }
        if (member.Kind == MemberKind.DateTimeOffset)
        {
            return "GetDateTimeOffset";
        }
        var bare = member.IsNullableValue ? member.TypeFqn.TrimEnd('?') : member.TypeFqn;
        return bare switch
        {
            "byte" => "GetByte",
            "sbyte" => "GetSByte",
            "short" => "GetInt16",
            "ushort" => "GetUInt16",
            "int" => "GetInt32",
            "uint" => "GetUInt32",
            "long" => "GetInt64",
            "ulong" => "GetUInt64",
            "float" => "GetSingle",
            "double" => "GetDouble",
            "decimal" => "GetDecimal",
            _ => "GetInt32",
        };
    }

    /// <summary>Reader locals: nullable so "missing" is representable for every kind.</summary>
    private static string LocalTypeFqn(this PayloadMember member)
        => member.Kind == MemberKind.String
            ? "string?"
            : member.IsNullableValue ? member.TypeFqn : member.TypeFqn;

    private static string Local(this PayloadMember member)
        => "__" + char.ToLowerInvariant(member.Name[0]) + member.Name.Substring(1);

    /// <summary>
    /// The default Tags expression for a registration (ADR 0022, additive): the empty set when no
    /// Labels are declared, otherwise JobTags.Empty.WithLabel(...) per declared Label in order. Only
    /// Labels are expressible — a Keyed-Tag default would require a separator (deferred).
    /// </summary>
    private static string DefaultTags(JobModel job)
        => job.Labels.Count == 0
            ? "global::BackWave.Storage.JobTags.Empty"
            : "global::BackWave.Storage.JobTags.Empty"
                + string.Concat(job.Labels.Select(label => $".WithLabel({Literal(label)})"));

    private static string WireClassFqn(JobModel job)
        => job.Namespace.Length == 0
            ? $"global::{job.JobTypeName}Wire"
            : $"global::{job.Namespace}.{job.JobTypeName}Wire";

    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
}
