using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace BackWave.SourceGenerators;

/// <summary>
/// Renders the generated source. Every shape here is exactly what a user would write by
/// hand: straight-line Utf8JsonWriter/Reader code (unknown JSON properties skipped, missing
/// ones defaulted — the tolerant-decode contract), a primary-constructor handler for method
/// sugar, and object-initializer JobRegistrations.
/// </summary>
internal static class JobEmitter
{
    private const string JsonElementFqn = "global::System.Text.Json.JsonElement";
    private const string NullableJsonElementFqn = JsonElementFqn + "?";

    private const string Header = """
        // <auto-generated/>
        // Generated by BackWave.SourceGenerators - exactly what you would write by hand.
        #nullable enable

        """;

    public static string EmitRegistry(
        IReadOnlyList<JobModel> jobs, IReadOnlyList<(string TypeFqn, string ContextFqn)> seedCodecs)
    {
        var source = new StringBuilder(Header);
        source.Append("""
            namespace BackWave.Generated
            {
                /// <summary>The generated Job Registry: every [Job] declaration in this assembly.</summary>
                public static class BackWaveJobs
                {
                    /// <summary>One registration per [Job], ordered by Wire Name.</summary>
                    public static global::System.Collections.Generic.IReadOnlyList<global::BackWave.Jobs.JobRegistration> CreateRegistrations()
                        => new global::BackWave.Jobs.JobRegistration[]
                        {

            """);
        foreach (var job in jobs)
        {
            source.Append($$"""
                            new global::BackWave.Jobs.JobRegistration
                            {
                                WireName = {{Literal(job.WireName)}},
                                JobType = typeof({{job.JobTypeFqn}}),
                                Queue = {{Literal(job.Queue)}},
                                DefaultTags = {{DefaultTags(job)}},

            """);
            if (job.RetryMaxAttempts > 0)
            {
                source.Append($$"""
                                    Retry = {{RetryExpression(job)}},

                """);
            }
            if (job.OutputContextFqn is { } outputContextFqn)
            {
                // The step's Job Output codec, referencing the consumer's own JsonSerializerContext - no
                // caller ever passes outputTypeInfo. GetTypeInfo returns the non-generic base, which is
                // exactly the type OutputTypeInfo holds.
                source.Append($$"""
                                    OutputTypeInfo = {{outputContextFqn}}.Default.GetTypeInfo(typeof({{job.OutputTypeFqn}})),

                """);
            }
            source.Append($$"""
                                Serialize = static job => {{WireClassFqn(job)}}.Serialize(({{job.JobTypeFqn}})job),
                                Deserialize = static payload => {{WireClassFqn(job)}}.Deserialize(payload),
                                Execute = static (services, job, context, cancellationToken) =>
                                    (services.GetService(typeof(global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}>)) is global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}> handler
                                        ? handler
                                        : throw new global::System.InvalidOperationException(
                                            "No IJobHandler<{{job.JobTypeName}}> is registered for wire name '{{job.WireName}}'."))
                                    .HandleAsync(({{job.JobTypeFqn}})job, context, cancellationToken),
                            },

            """);
        }
        // Close the registrations array with a trailing blank line before the next member. The blank is
        // written explicitly: a raw string's final blank line collapses, and EmitSeedCodecs may sit here.
        source.Append("            };\n\n");
        EmitSeedCodecs(source, seedCodecs);
        source.Append($$"""
                    /// <summary>The registry over <see cref="CreateRegistrations"/>.</summary>
                    public static global::BackWave.Jobs.JobRegistry CreateRegistry()
                        => new global::BackWave.Jobs.JobRegistry(CreateRegistrations(){{(seedCodecs.Count > 0 ? ", CreateSeedCodecs()" : "")}});

                    /// <summary>
                    /// The DI-free module: the registrations, one (IJobHandler&lt;T&gt;, THandler) handler
                    /// mapping per [Job], and the classes that declare method-sugar [Job]s — all ordered by
                    /// Wire Name. Pass to UseJobs to register the registry, every handler (scoped), and every
                    /// declaring class (scoped) in one call.
                    /// </summary>
                    public static global::BackWave.Jobs.JobModule Module
                        => new global::BackWave.Jobs.JobModule
                        {
                            Registrations = CreateRegistrations(),

            """);
        if (seedCodecs.Count > 0)
        {
            source.Append("""
                            SeedCodecs = CreateSeedCodecs(),

            """);
        }
        source.Append("""
                            Handlers = new global::BackWave.Jobs.JobHandlerMapping[]
                            {

            """);
        foreach (var job in jobs)
        {
            source.Append($$"""
                                new global::BackWave.Jobs.JobHandlerMapping(typeof(global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}>), typeof({{job.HandlerTypeFqn}})),

            """);
        }
        source.Append("""
                            },
                            ContainingTypes = new global::BackWave.Jobs.JobContainingType[]
                            {

            """);
        // The declaring classes of NON-static method-sugar jobs: the generated …Handler ctor-injects
        // one and forwards to it, so it is the job's DI entry. Static-method sugar calls statically
        // (no instance) and class-based handlers are already in Handlers — neither contributes one.
        // Distinct + ordered so the list is stable; the array stays empty when there are none.
        var containingTypes = jobs
            .Where(job => job.Sugar is { IsStatic: false })
            .Select(job => job.Sugar!.ContainingTypeFqn)
            .Distinct()
            .OrderBy(fqn => fqn, System.StringComparer.Ordinal);
        foreach (var containingType in containingTypes)
        {
            source.Append($$"""
                                typeof({{containingType}}),

            """);
        }
        source.Append("""
                            },
                        };
                }
            }

            """);
        return source.ToString();
    }

    /// <summary>
    /// The Workflow Input seed codec map, keyed by seed type - one entry per seed, each referencing the
    /// consumer's own JsonSerializerContext, so a started workflow reads and writes its seed with no
    /// caller-passed serializer. Emitted only when at least one seed is declared; otherwise nothing is
    /// written and the registry/module carry no seed map (older-shaped, source-compatible).
    /// </summary>
    private static void EmitSeedCodecs(
        StringBuilder source, IReadOnlyList<(string TypeFqn, string ContextFqn)> seedCodecs)
    {
        if (seedCodecs.Count == 0)
        {
            return;
        }
        source.Append("""
                    /// <summary>The Workflow Input seed codecs, keyed by seed type - one per declared seed.</summary>
                    public static global::System.Collections.Generic.IReadOnlyDictionary<global::System.Type, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo> CreateSeedCodecs()
                        => new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo>
                        {

            """);
        foreach (var (typeFqn, contextFqn) in seedCodecs)
        {
            source.Append($$"""
                            [typeof({{typeFqn}})] = {{contextFqn}}.Default.GetTypeInfo(typeof({{typeFqn}}))!,

            """);
        }
        // Close the dictionary initializer; explicit trailing blank line separates this method from the
        // CreateRegistry summary that follows (a raw string's final blank line would collapse).
        source.Append("                        };\n\n");
    }

    public static string EmitJob(JobModel job)
    {
        var source = new StringBuilder(Header);
        var hasNamespace = job.Namespace.Length > 0;
        if (hasNamespace)
        {
            source.Append($"namespace {job.Namespace}\n{{\n");
        }

        if (job.Sugar is { } sugar)
        {
            EmitSugarRecord(source, job, sugar);
            EmitSugarHandler(source, job, sugar);
        }
        EmitWireClass(source, job);

        if (hasNamespace)
        {
            source.Append("}\n");
        }
        return source.ToString();
    }

    private static void EmitSugarRecord(StringBuilder source, JobModel job, MethodSugar sugar)
    {
        var parameters = string.Join(", ", job.Members
            .OrderBy(m => m.CtorPosition)
            .Select(m => $"{m.TypeFqn} {m.Name}"));
        source.Append($$"""
                /// <summary>Generated payload for [Job] "{{job.WireName}}".</summary>
                {{sugar.Accessibility}} sealed record {{job.JobTypeName}}({{parameters}});


            """);
    }

    private static void EmitSugarHandler(StringBuilder source, JobModel job, MethodSugar sugar)
    {
        var arguments = string.Join(", ", sugar.CallArguments
            .Select(a => a is "context" or "cancellationToken" ? a : $"job.{a}"));
        var call = sugar.IsStatic
            ? $"{sugar.ContainingTypeFqn}.{sugar.MethodName}({arguments})"
            : $"target.{sugar.MethodName}({arguments})";
        var declaration = sugar.IsStatic
            ? $"{sugar.Accessibility} sealed class {job.JobTypeName}Handler"
            : $"{sugar.Accessibility} sealed class {job.JobTypeName}Handler({sugar.ContainingTypeFqn} target)";
        source.Append($$"""
                /// <summary>Generated handler for [Job] "{{job.WireName}}".</summary>
                {{declaration}} : global::BackWave.Jobs.IJobHandler<{{job.JobTypeFqn}}>
                {
                    public global::System.Threading.Tasks.Task HandleAsync(
                        {{job.JobTypeFqn}} job,
                        global::BackWave.Jobs.JobContext context,
                        global::System.Threading.CancellationToken cancellationToken)
                        => {{call}};
                }


            """);
    }

    private static void EmitWireClass(StringBuilder source, JobModel job)
    {
        source.Append($$"""
                /// <summary>Generated wire format for [Job] "{{job.WireName}}".</summary>
                internal static class {{job.JobTypeName}}Wire
                {
            {{TypeInfoFields(job)}}{{MaxDepthField(job)}}{{MemberPathHelper(job)}}        public static byte[] Serialize({{job.JobTypeFqn}} value)
                    {
                        var buffer = new global::System.IO.MemoryStream();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(buffer{{WriterOptions(job)}}))
                        {
                            writer.WriteStartObject();

            """);
        foreach (var member in job.Members)
        {
            EmitWrite(source, member);
        }
        source.Append($$"""
                            writer.WriteEndObject();
                        }
                        return buffer.ToArray();
                    }

                    public static {{job.JobTypeFqn}} Deserialize(global::System.ReadOnlyMemory<byte> payload)
                    {
                        var reader = new global::System.Text.Json.Utf8JsonReader(payload.Span{{ReaderOptions(job)}});

            """);
        foreach (var member in job.Members)
        {
            source.Append($"            {member.LocalTypeFqn()} {member.Local()} = {member.MissingLiteral};\n");
        }
        source.Append("""

                        if (!reader.Read() || reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)
                        {
                            throw new global::System.Text.Json.JsonException("Expected a JSON object.");
                        }
                        while (reader.Read() && reader.TokenType == global::System.Text.Json.JsonTokenType.PropertyName)
                        {

            """);
        var first = true;
        foreach (var member in job.Members)
        {
            EmitRead(source, member, first);
            first = false;
        }

        // Skip unknown / unmodeled properties. With at least one member this is the trailing `else`
        // of the property if/else-if chain; with no members (a job whose payload carries no data)
        // every property is unknown, so the skip is unconditional — an `else` with no preceding `if`
        // would not compile.
        source.Append(job.Members.Count == 0
            ? """
                            reader.Read();
                            reader.Skip();
                        }

            """
            : """
                            else
                            {
                                reader.Read();
                                reader.Skip();
                            }
                        }

            """);

        var ctorArguments = string.Join(", ", job.Members
            .Where(m => m.CtorPosition >= 0)
            .OrderBy(m => m.CtorPosition)
            .Select(m => NeedsNullForgiving(m) ? $"{m.Local()}!" : m.Local()));
        var initProps = job.Members.Where(m => m.CtorPosition < 0).ToList();
        var initializer = initProps.Count == 0
            ? ""
            : " { " + string.Join(", ", initProps.Select(m =>
                $"{m.Name} = {(NeedsNullForgiving(m) ? m.Local() + "!" : m.Local())}")) + " }";
        source.Append($$"""
                        return new {{job.JobTypeFqn}}({{ctorArguments}}){{initializer}};
                    }
                }

            """);
    }

    /// <summary>
    /// One JsonTypeInfo property per delegated member, read from the JsonSerializerContext that serves the
    /// member type on first use and cached once found. A context that has no metadata for the type fails only
    /// the call that needs it, with a plain exception: a static initializer would poison the wire class instead.
    /// The cache write is a benign race - every racer stores the same context-owned metadata.
    /// </summary>
    private static string TypeInfoFields(JobModel job)
    {
        var fields = new StringBuilder();
        foreach (var member in job.Members)
        {
            if (member.Delegation is not { ContextFqn: { } contextFqn } delegation)
            {
                continue;
            }
            var infoType = $"global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{delegation.InfoTypeFqn}>";
            var context = BackWaveGenerator.DisplayFqn(contextFqn);
            var type = BackWaveGenerator.DisplayFqn(delegation.TypeFqn);
            var message = Literal(
                $"Member '{member.SourceName}' of job payload '{job.JobTypeName}' ([Job] \"{job.WireName}\") cannot be serialized: " +
                $"JsonSerializerContext '{context}' has no metadata for type '{type}'. Add " +
                $"[JsonSerializable(typeof({type}))] to '{context}', or {JobDiagnostics.RegisterJobByHand}.");
            fields.Append($$"""
                        private static {{infoType}}? {{member.TypeInfoCache()}};

                        private static {{infoType}} {{member.TypeInfoField()}}
                            => {{member.TypeInfoCache()}} ??= {{contextFqn}}.Default.GetTypeInfo(typeof({{delegation.TypeFqn}})) as {{infoType}}
                                ?? throw new global::System.InvalidOperationException({{message}});


                """);
        }
        return fields.ToString();
    }

    /// <summary>
    /// The depth limit for a payload with a delegated member. A source-generated context writes through a fast
    /// path that ignores its MaxDepth, so the codec bounds the writer and the reader with one value: the largest
    /// context limit, plus one level for the payload object. Else a deep member enqueues and never decodes. A
    /// context limit of int.MaxValue keeps the sum in range.
    /// </summary>
    private static string MaxDepthField(JobModel job)
    {
        // A context MaxDepth of 0 means the STJ default of 64.
        var depths = job.Members
            .Select(m => m.Delegation?.ContextFqn)
            .OfType<string>()
            .Select(contextFqn => $"{contextFqn}.Default.Options.MaxDepth")
            .Distinct()
            .Select(depth => $"({depth} > 0 ? {depth} : 64)")
            .ToList();
        return depths.Count == 0
            ? ""
            : $$"""
                    private static int MaxDepth => global::System.Math.Min({{depths.Aggregate((max, depth) => $"global::System.Math.Max({max}, {depth})")}}, int.MaxValue - 1) + 1;


            """;
    }

    private static string WriterOptions(JobModel job)
        => job.Members.Any(m => m.Kind == MemberKind.Delegated)
            ? ", new global::System.Text.Json.JsonWriterOptions { MaxDepth = MaxDepth }"
            : "";

    private static string ReaderOptions(JobModel job)
        => job.Members.Any(m => m.Kind == MemberKind.Delegated)
            ? ", new global::System.Text.Json.JsonReaderOptions { MaxDepth = MaxDepth }"
            : "";

    /// <summary>
    /// The helpers that write and read one delegated member, and name the member in any exception: AtMember
    /// re-roots a JsonException at the payload, so its path reads "$.Member.Inner" and not "$.Inner", and wraps
    /// any other exception in an InvalidOperationException that starts with the member path. A write message
    /// has no line number and ends with the path and a period. An OutOfMemoryException is fatal, so it goes
    /// out unwrapped. The JsonTypeInfo argument is read before the try, so a context with no metadata keeps its
    /// own message. Emitted only for a payload with a delegated member.
    /// </summary>
    private static string MemberPathHelper(JobModel job)
        => !job.Members.Any(m => m.Kind == MemberKind.Delegated)
            ? ""
            : """
                    private static void WriteMember<T>(global::System.Text.Json.Utf8JsonWriter writer, T value, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> typeInfo, string member)
                    {
                        try
                        {
                            global::System.Text.Json.JsonSerializer.Serialize(writer, value, typeInfo);
                        }
                        catch (global::System.Exception exception) when (exception is not global::System.OutOfMemoryException)
                        {
                            throw AtMember(exception, member, "write");
                        }
                    }

                    private static T? ReadMember<T>(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> typeInfo, string member)
                    {
                        try
                        {
                            return global::System.Text.Json.JsonSerializer.Deserialize(ref reader, typeInfo);
                        }
                        catch (global::System.Exception exception) when (exception is not global::System.OutOfMemoryException)
                        {
                            throw AtMember(exception, member, "read");
                        }
                    }

                    private static global::System.Exception AtMember(global::System.Exception exception, string member, string action)
                    {
                        if (exception is not global::System.Text.Json.JsonException json)
                        {
                            return new global::System.InvalidOperationException("Could not " + action + " member $." + member + ": " + exception.Message, exception);
                        }
                        var path = "$." + member + json.Path?.Substring(1);
                        var end = json.LineNumber is null ? "." : " ";
                        var message = json.Path is null
                            ? json.Message
                            : json.Message.Replace("Path: " + json.Path + end, "Path: " + path + end);
                        return new global::System.Text.Json.JsonException(message, path, json.LineNumber, json.BytePositionInLine, json);
                    }


            """;

    /// <summary>
    /// A local that holds null only when the JSON omits the member, for a member type that is not nullable.
    /// The tolerant decode passes it on with the null-forgiving operator, as a string member does.
    /// </summary>
    private static bool NeedsNullForgiving(PayloadMember member)
        => member.ParameterTypeFqn is not null
            ? member.ParameterIsUnannotatedReference
            : (member.Kind == MemberKind.String && !member.IsNullableValue)
                || member.Delegation is { IsUnannotatedReference: true };

    private static void EmitWrite(StringBuilder source, PayloadMember member)
    {
        var name = Literal(member.Name);
        var value = $"value.{member.Name}";
        if (member.Delegation is { } delegation)
        {
            var serialize = $"WriteMember(writer, {value}, {member.TypeInfoField()}, {name})";
            // An unset JsonElement is Undefined, which STJ cannot write. It writes as null, so it reads back as a
            // JsonElement of kind Null, and a JsonElement? reads back as null.
            // An unset ImmutableArray is default, which STJ cannot write either. It writes as null, which the reader
            // never hands to STJ, so it reads back as the default.
            var isNull = delegation switch
            {
                { TypeFqn: JsonElementFqn } => $"{value}.ValueKind == global::System.Text.Json.JsonValueKind.Undefined",
                { TypeFqn: NullableJsonElementFqn } => $"{value}.GetValueOrDefault().ValueKind == global::System.Text.Json.JsonValueKind.Undefined",
                { IsImmutableArray: true, IsNullableValue: true } => $"{value}.GetValueOrDefault().IsDefault",
                { IsImmutableArray: true } => $"{value}.IsDefault",
                { CanBeNull: true } => $"{value} is null",
                _ => null,
            };
            source.Append(isNull is not null
                ? $$"""
                            if ({{isNull}})
                            {
                                writer.WriteNull({{name}});
                            }
                            else
                            {
                                writer.WritePropertyName({{name}});
                                {{serialize}};
                            }

            """
                : $$"""
                            writer.WritePropertyName({{name}});
                            {{serialize}};

            """);
            return;
        }
        if (member.IsNullableValue)
        {
            source.Append($$"""
                            if ({{value}}.HasValue)
                            {
                                {{WriteCall(member.Kind, name, value + ".Value")}};
                            }
                            else
                            {
                                writer.WriteNull({{name}});
                            }

            """);
            return;
        }
        if (member.Kind == MemberKind.String)
        {
            source.Append($$"""
                            if ({{value}} is null)
                            {
                                writer.WriteNull({{name}});
                            }
                            else
                            {
                                writer.WriteString({{name}}, {{value}});
                            }

            """);
            return;
        }
        source.Append($"                {WriteCall(member.Kind, name, value)};\n");
    }

    private static string WriteCall(MemberKind kind, string name, string value)
        => kind switch
        {
            MemberKind.Boolean => $"writer.WriteBoolean({name}, {value})",
            MemberKind.Number => $"writer.WriteNumber({name}, {value})",
            MemberKind.Enum => $"writer.WriteString({name}, {value}.ToString())",
            _ => $"writer.WriteString({name}, {value})", // string, Guid, DateTime, DateTimeOffset
        };

    private static void EmitRead(StringBuilder source, PayloadMember member, bool first)
    {
        var keyword = first ? "if" : "else if";
        var local = member.Local();
        string assignment;
        if (member.Delegation is { } delegation)
        {
            var read = $"{local} = ReadMember(ref reader, {member.TypeInfoField()}, {Literal(member.Name)});";
            // A JSON null reads as the default of the member. A JsonElement is the exception: there a JSON null
            // is a value.
            assignment = delegation.TypeFqn == JsonElementFqn
                ? $$"""
                                    {{read}}
                """
                : $$"""
                                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                                    {
                                        {{read}}
                                    }
                """;
        }
        else if (member.Kind == MemberKind.Enum)
        {
            var enumType = member.IsNullableValue ? member.TypeFqn.TrimEnd('?') : member.TypeFqn;
            // Strict decode: match the numeric/Guid/DateTime paths and throw on an
            // unparseable token instead of silently defaulting (e.g. a renamed enum
            // member across versions would otherwise become default(TEnum) with no signal).
            // A nullable enum still accepts a JSON null (the writer emits one for HasValue == false).
            var strict = $$"""
                                    if (reader.TokenType == global::System.Text.Json.JsonTokenType.String
                                        && global::System.Enum.TryParse<{{enumType}}>(reader.GetString(), out var {{local}}Parsed))
                                    {
                                        {{local}} = {{local}}Parsed;
                                    }
                                    else
                                    {
                                        throw new global::System.Text.Json.JsonException("Could not decode property '{{member.Name}}' as enum '{{enumType}}'.");
                                    }
                """;
            assignment = member.IsNullableValue
                ? $$"""
                                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                                    {
                                    {{strict}}
                                    }
                """
                : strict;
        }
        else if (member.Kind == MemberKind.String)
        {
            assignment = $$"""
                                    {{local}} = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : reader.GetString();
                """;
        }
        else
        {
            var read = $"reader.{ReadCall(member)}()";
            assignment = member.IsNullableValue
                ? $$"""
                                    {{local}} = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : {{read}};
                """
                : $$"""
                                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                                    {
                                        {{local}} = {{read}};
                                    }
                """;
        }
        source.Append($$"""
                            {{keyword}} (reader.ValueTextEquals({{Literal(member.Name)}}))
                            {
                                reader.Read();
            {{assignment}}
                            }

            """);
    }

    private static string ReadCall(PayloadMember member)
    {
        if (member.Kind == MemberKind.Boolean)
        {
            return "GetBoolean";
        }
        if (member.Kind == MemberKind.Guid)
        {
            return "GetGuid";
        }
        if (member.Kind == MemberKind.DateTime)
        {
            return "GetDateTime";
        }
        if (member.Kind == MemberKind.DateTimeOffset)
        {
            return "GetDateTimeOffset";
        }
        var bare = member.IsNullableValue ? member.TypeFqn.TrimEnd('?') : member.TypeFqn;
        return bare switch
        {
            "byte" => "GetByte",
            "sbyte" => "GetSByte",
            "short" => "GetInt16",
            "ushort" => "GetUInt16",
            "int" => "GetInt32",
            "uint" => "GetUInt32",
            "long" => "GetInt64",
            "ulong" => "GetUInt64",
            "float" => "GetSingle",
            "double" => "GetDouble",
            "decimal" => "GetDecimal",
            _ => "GetInt32",
        };
    }

    /// <summary>Reader locals: nullable so "missing" is representable for every kind.</summary>
    private static string LocalTypeFqn(this PayloadMember member)
        => member switch
        {
            { ParameterTypeFqn: { } parameterType } => member.ParameterIsUnannotatedReference
                ? parameterType + "?"
                : parameterType,
            { Delegation: { IsReferenceType: true } delegation } => delegation.InfoTypeFqn + "?",
            { Delegation: { } delegation } => delegation.InfoTypeFqn,
            { Kind: MemberKind.String } => "string?",
            _ => member.TypeFqn,
        };

    private static string TypeInfoField(this PayloadMember member) => member.Name + "TypeInfo";

    private static string TypeInfoCache(this PayloadMember member) => member.Local() + "TypeInfo";

    private static string Local(this PayloadMember member)
        => "__" + char.ToLowerInvariant(member.Name[0]) + member.Name.Substring(1);

    /// <summary>
    /// The default Tags expression for a registration (ADR 0022, additive): the empty set when no
    /// Labels are declared, otherwise JobTags.Empty.WithLabel(...) per declared Label in order. Only
    /// Labels are expressible — a Keyed-Tag default would require a separator (deferred).
    /// </summary>
    private static string DefaultTags(JobModel job)
        => job.Labels.Count == 0
            ? "global::BackWave.Storage.JobTags.Empty"
            : "global::BackWave.Storage.JobTags.Empty"
                + string.Concat(job.Labels.Select(label => $".WithLabel({Literal(label)})"));

    /// <summary>
    /// The per-job retry override expression for a registration (ADR 0051): a
    /// RetryDisposition.FromIntervals call built from the [Retry] ceiling and intervals. Validation
    /// (non-empty, at most 20 intervals) runs inside FromIntervals at registration time. Only called
    /// when the job declares a [Retry] override.
    /// </summary>
    private static string RetryExpression(JobModel job)
    {
        var intervals = string.Join(", ", job.RetryBackoffSeconds.Select(seconds =>
            $"global::System.TimeSpan.FromSeconds({seconds.ToString("R", CultureInfo.InvariantCulture)}d)"));
        return $"global::BackWave.Core.RetryDisposition.FromIntervals({job.RetryMaxAttempts}, "
            + $"new global::System.TimeSpan[] {{ {intervals} }})";
    }

    private static string WireClassFqn(JobModel job)
        => job.Namespace.Length == 0
            ? $"global::{job.JobTypeName}Wire"
            : $"global::{job.Namespace}.{job.JobTypeName}Wire";

    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
}
