// <auto-generated/>
// Generated by BackWave.SourceGenerators — exactly what you would write by hand.
#nullable enable
namespace Acme.Jobs
{
    /// <summary>Generated payload for [Job] "send-welcome".</summary>
    public sealed record SendWelcome(string UserId, int Retries);

    /// <summary>Generated handler for [Job] "send-welcome".</summary>
    public sealed class SendWelcomeHandler(global::Acme.Jobs.Notifications target) : global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.SendWelcome>
    {
        public global::System.Threading.Tasks.Task HandleAsync(
            global::Acme.Jobs.SendWelcome job,
            global::BackWave.Jobs.JobContext context,
            global::System.Threading.CancellationToken cancellationToken)
            => target.SendWelcomeAsync(job.UserId, job.Retries, context, cancellationToken);
    }

    /// <summary>Generated wire format for [Job] "send-welcome".</summary>
    internal static class SendWelcomeWire
    {
        public static byte[] Serialize(global::Acme.Jobs.SendWelcome value)
        {
            var buffer = new global::System.IO.MemoryStream();
            using (var writer = new global::System.Text.Json.Utf8JsonWriter(buffer))
            {
                writer.WriteStartObject();
                if (value.UserId is null)
                {
                    writer.WriteNull("UserId");
                }
                else
                {
                    writer.WriteString("UserId", value.UserId);
                }
                writer.WriteNumber("Retries", value.Retries);
                writer.WriteEndObject();
            }
            return buffer.ToArray();
        }

        public static global::Acme.Jobs.SendWelcome Deserialize(global::System.ReadOnlyMemory<byte> payload)
        {
            var reader = new global::System.Text.Json.Utf8JsonReader(payload.Span);
            string? __userId = null;
            int __retries = default;

            if (!reader.Read() || reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)
            {
                throw new global::System.Text.Json.JsonException("Expected a JSON object.");
            }
            while (reader.Read() && reader.TokenType == global::System.Text.Json.JsonTokenType.PropertyName)
            {
                if (reader.ValueTextEquals("UserId"))
                {
                    reader.Read();
                    __userId = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : reader.GetString();
                }
                else if (reader.ValueTextEquals("Retries"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __retries = reader.GetInt32();
                    }
                }
                else
                {
                    reader.Read();
                    reader.Skip();
                }
            }
            return new global::Acme.Jobs.SendWelcome(__userId!, __retries);
        }
    }
}
