// <auto-generated/>
// Generated by BackWave.SourceGenerators — exactly what you would write by hand.
#nullable enable
namespace BackWave.Generated
{
    /// <summary>The generated Job Registry: every [Job] declaration in this assembly.</summary>
    public static class BackWaveJobs
    {
        /// <summary>One registration per [Job], ordered by Wire Name.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::BackWave.Jobs.JobRegistration> CreateRegistrations()
            => new global::BackWave.Jobs.JobRegistration[]
            {
                new global::BackWave.Jobs.JobRegistration
                {
                    WireName = "charge-card",
                    JobType = typeof(global::Acme.Jobs.ChargeCard),
                    Queue = "payments",
                    DefaultTags = global::BackWave.Storage.JobTags.Empty,
                    Serialize = static job => global::Acme.Jobs.ChargeCardWire.Serialize((global::Acme.Jobs.ChargeCard)job),
                    Deserialize = static payload => global::Acme.Jobs.ChargeCardWire.Deserialize(payload),
                    Execute = static (services, job, context, cancellationToken) =>
                        (services.GetService(typeof(global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.ChargeCard>)) is global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.ChargeCard> handler
                            ? handler
                            : throw new global::System.InvalidOperationException(
                                "No IJobHandler<ChargeCard> is registered for wire name 'charge-card'."))
                        .HandleAsync((global::Acme.Jobs.ChargeCard)job, context, cancellationToken),
                },
                new global::BackWave.Jobs.JobRegistration
                {
                    WireName = "send-welcome",
                    JobType = typeof(global::Acme.Jobs.SendWelcome),
                    Queue = "default",
                    DefaultTags = global::BackWave.Storage.JobTags.Empty,
                    Serialize = static job => global::Acme.Jobs.SendWelcomeWire.Serialize((global::Acme.Jobs.SendWelcome)job),
                    Deserialize = static payload => global::Acme.Jobs.SendWelcomeWire.Deserialize(payload),
                    Execute = static (services, job, context, cancellationToken) =>
                        (services.GetService(typeof(global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.SendWelcome>)) is global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.SendWelcome> handler
                            ? handler
                            : throw new global::System.InvalidOperationException(
                                "No IJobHandler<SendWelcome> is registered for wire name 'send-welcome'."))
                        .HandleAsync((global::Acme.Jobs.SendWelcome)job, context, cancellationToken),
                },
            };

        /// <summary>The registry over <see cref="CreateRegistrations"/>.</summary>
        public static global::BackWave.Jobs.JobRegistry CreateRegistry()
            => new global::BackWave.Jobs.JobRegistry(CreateRegistrations());

        /// <summary>
        /// The DI-free module: the registrations, one (IJobHandler&lt;T&gt;, THandler) handler
        /// mapping per [Job], and the classes that declare method-sugar [Job]s — all ordered by
        /// Wire Name. Pass to UseJobs to register the registry, every handler (scoped), and every
        /// declaring class (scoped) in one call.
        /// </summary>
        public static global::BackWave.Jobs.JobModule Module
            => new global::BackWave.Jobs.JobModule
            {
                Registrations = CreateRegistrations(),
                Handlers = new global::BackWave.Jobs.JobHandlerMapping[]
                {
                    new global::BackWave.Jobs.JobHandlerMapping(typeof(global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.ChargeCard>), typeof(global::Acme.Jobs.ChargeCardHandler)),
                    new global::BackWave.Jobs.JobHandlerMapping(typeof(global::BackWave.Jobs.IJobHandler<global::Acme.Jobs.SendWelcome>), typeof(global::Acme.Jobs.SendWelcomeHandler)),
                },
                ContainingTypes = new global::BackWave.Jobs.JobContainingType[]
                {
                    typeof(global::Acme.Jobs.Notifications),
                },
            };
    }
}
