// <auto-generated/>
// Generated by BackWave.SourceGenerators - exactly what you would write by hand.
#nullable enable
namespace Acme.Orders
{
    /// <summary>Generated wire format for [Job] "ship-order".</summary>
    internal static class ShipOrderWire
    {
        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<string>>? __skusTypeInfo;

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<string>> SkusTypeInfo
            => __skusTypeInfo ??= global::Acme.Orders.OrdersJson.Default.GetTypeInfo(typeof(global::System.Collections.Generic.List<string>)) as global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<string>>
                ?? throw new global::System.InvalidOperationException("Member 'Skus' of job payload 'ShipOrder' ([Job] \"ship-order\") cannot be serialized: JsonSerializerContext 'Acme.Orders.OrdersJson' has no metadata for type 'System.Collections.Generic.List<string>'. Add [JsonSerializable(typeof(System.Collections.Generic.List<string>))] to 'Acme.Orders.OrdersJson', or register this job by hand with JobRegistration.Create.");

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, int>>? __countsTypeInfo;

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, int>> CountsTypeInfo
            => __countsTypeInfo ??= global::Acme.Orders.OrdersJson.Default.GetTypeInfo(typeof(global::System.Collections.Generic.Dictionary<string, int>)) as global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<string, int>>
                ?? throw new global::System.InvalidOperationException("Member 'Counts' of job payload 'ShipOrder' ([Job] \"ship-order\") cannot be serialized: JsonSerializerContext 'Acme.Orders.OrdersJson' has no metadata for type 'System.Collections.Generic.Dictionary<string, int>'. Add [JsonSerializable(typeof(System.Collections.Generic.Dictionary<string, int>))] to 'Acme.Orders.OrdersJson', or register this job by hand with JobRegistration.Create.");

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Acme.Orders.Address>? __shipTypeInfo;

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Acme.Orders.Address> ShipTypeInfo
            => __shipTypeInfo ??= global::Acme.Orders.OrdersJson.Default.GetTypeInfo(typeof(global::Acme.Orders.Address)) as global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Acme.Orders.Address>
                ?? throw new global::System.InvalidOperationException("Member 'Ship' of job payload 'ShipOrder' ([Job] \"ship-order\") cannot be serialized: JsonSerializerContext 'Acme.Orders.OrdersJson' has no metadata for type 'Acme.Orders.Address'. Add [JsonSerializable(typeof(Acme.Orders.Address))] to 'Acme.Orders.OrdersJson', or register this job by hand with JobRegistration.Create.");

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Acme.Orders.Address>>? __historyTypeInfo;

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Acme.Orders.Address>> HistoryTypeInfo
            => __historyTypeInfo ??= global::Acme.Orders.OrdersJson.Default.GetTypeInfo(typeof(global::System.Collections.Generic.IReadOnlyList<global::Acme.Orders.Address>)) as global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.IReadOnlyList<global::Acme.Orders.Address>>
                ?? throw new global::System.InvalidOperationException("Member 'History' of job payload 'ShipOrder' ([Job] \"ship-order\") cannot be serialized: JsonSerializerContext 'Acme.Orders.OrdersJson' has no metadata for type 'System.Collections.Generic.IReadOnlyList<Acme.Orders.Address>'. Add [JsonSerializable(typeof(System.Collections.Generic.IReadOnlyList<Acme.Orders.Address>))] to 'Acme.Orders.OrdersJson', or register this job by hand with JobRegistration.Create.");

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int[]>? __binsTypeInfo;

        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int[]> BinsTypeInfo
            => __binsTypeInfo ??= global::Acme.Orders.OrdersJson.Default.GetTypeInfo(typeof(int[])) as global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int[]>
                ?? throw new global::System.InvalidOperationException("Member 'Bins' of job payload 'ShipOrder' ([Job] \"ship-order\") cannot be serialized: JsonSerializerContext 'Acme.Orders.OrdersJson' has no metadata for type 'int[]'. Add [JsonSerializable(typeof(int[]))] to 'Acme.Orders.OrdersJson', or register this job by hand with JobRegistration.Create.");

        private static int MaxDepth => global::System.Math.Min((global::Acme.Orders.OrdersJson.Default.Options.MaxDepth > 0 ? global::Acme.Orders.OrdersJson.Default.Options.MaxDepth : 64), int.MaxValue - 1) + 1;

        private static void WriteMember<T>(global::System.Text.Json.Utf8JsonWriter writer, T value, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> typeInfo, string member)
        {
            try
            {
                global::System.Text.Json.JsonSerializer.Serialize(writer, value, typeInfo);
            }
            catch (global::System.Exception exception) when (exception is not global::System.OutOfMemoryException)
            {
                throw AtMember(exception, member, "write");
            }
        }

        private static T? ReadMember<T>(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T> typeInfo, string member)
        {
            try
            {
                return global::System.Text.Json.JsonSerializer.Deserialize(ref reader, typeInfo);
            }
            catch (global::System.Exception exception) when (exception is not global::System.OutOfMemoryException)
            {
                throw AtMember(exception, member, "read");
            }
        }

        private static global::System.Exception AtMember(global::System.Exception exception, string member, string action)
        {
            if (exception is not global::System.Text.Json.JsonException json)
            {
                return new global::System.InvalidOperationException("Could not " + action + " member $." + member + ": " + exception.Message, exception);
            }
            var path = "$." + member + json.Path?.Substring(1);
            var end = json.LineNumber is null ? "." : " ";
            var message = json.Path is null
                ? json.Message
                : json.Message.Replace("Path: " + json.Path + end, "Path: " + path + end);
            return new global::System.Text.Json.JsonException(message, path, json.LineNumber, json.BytePositionInLine, json);
        }

        public static byte[] Serialize(global::Acme.Orders.ShipOrder value)
        {
            var buffer = new global::System.IO.MemoryStream();
            using (var writer = new global::System.Text.Json.Utf8JsonWriter(buffer, new global::System.Text.Json.JsonWriterOptions { MaxDepth = MaxDepth }))
            {
                writer.WriteStartObject();
                writer.WriteString("Id", value.Id);
                writer.WriteString("Priority", value.Priority.ToString());
                if (value.Skus is null)
                {
                    writer.WriteNull("Skus");
                }
                else
                {
                    writer.WritePropertyName("Skus");
                    WriteMember(writer, value.Skus, SkusTypeInfo, "Skus");
                }
                if (value.Counts is null)
                {
                    writer.WriteNull("Counts");
                }
                else
                {
                    writer.WritePropertyName("Counts");
                    WriteMember(writer, value.Counts, CountsTypeInfo, "Counts");
                }
                if (value.Ship is null)
                {
                    writer.WriteNull("Ship");
                }
                else
                {
                    writer.WritePropertyName("Ship");
                    WriteMember(writer, value.Ship, ShipTypeInfo, "Ship");
                }
                if (value.History is null)
                {
                    writer.WriteNull("History");
                }
                else
                {
                    writer.WritePropertyName("History");
                    WriteMember(writer, value.History, HistoryTypeInfo, "History");
                }
                if (value.Bins is null)
                {
                    writer.WriteNull("Bins");
                }
                else
                {
                    writer.WritePropertyName("Bins");
                    WriteMember(writer, value.Bins, BinsTypeInfo, "Bins");
                }
                writer.WriteEndObject();
            }
            return buffer.ToArray();
        }

        public static global::Acme.Orders.ShipOrder Deserialize(global::System.ReadOnlyMemory<byte> payload)
        {
            var reader = new global::System.Text.Json.Utf8JsonReader(payload.Span, new global::System.Text.Json.JsonReaderOptions { MaxDepth = MaxDepth });
            global::System.Guid __id = default;
            global::Acme.Orders.Priority __priority = default;
            global::System.Collections.Generic.List<string>? __skus = null;
            global::System.Collections.Generic.Dictionary<string, int>? __counts = null;
            global::Acme.Orders.Address? __ship = null;
            global::System.Collections.Generic.IReadOnlyList<global::Acme.Orders.Address>? __history = null;
            int[]? __bins = null;

            if (!reader.Read() || reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)
            {
                throw new global::System.Text.Json.JsonException("Expected a JSON object.");
            }
            while (reader.Read() && reader.TokenType == global::System.Text.Json.JsonTokenType.PropertyName)
            {
                if (reader.ValueTextEquals("Id"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __id = reader.GetGuid();
                    }
                }
                else if (reader.ValueTextEquals("Priority"))
                {
                    reader.Read();
                    if (reader.TokenType == global::System.Text.Json.JsonTokenType.String
                        && global::System.Enum.TryParse<global::Acme.Orders.Priority>(reader.GetString(), out var __priorityParsed))
                    {
                        __priority = __priorityParsed;
                    }
                    else
                    {
                        throw new global::System.Text.Json.JsonException("Could not decode property 'Priority' as enum 'global::Acme.Orders.Priority'.");
                    }
                }
                else if (reader.ValueTextEquals("Skus"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __skus = ReadMember(ref reader, SkusTypeInfo, "Skus");
                    }
                }
                else if (reader.ValueTextEquals("Counts"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __counts = ReadMember(ref reader, CountsTypeInfo, "Counts");
                    }
                }
                else if (reader.ValueTextEquals("Ship"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __ship = ReadMember(ref reader, ShipTypeInfo, "Ship");
                    }
                }
                else if (reader.ValueTextEquals("History"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __history = ReadMember(ref reader, HistoryTypeInfo, "History");
                    }
                }
                else if (reader.ValueTextEquals("Bins"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __bins = ReadMember(ref reader, BinsTypeInfo, "Bins");
                    }
                }
                else
                {
                    reader.Read();
                    reader.Skip();
                }
            }
            return new global::Acme.Orders.ShipOrder(__id, __priority, __skus!, __counts!, __ship, __history!, __bins!);
        }
    }
}
