// <auto-generated/>
// Generated by BackWave.SourceGenerators — exactly what you would write by hand.
#nullable enable
namespace Acme.Jobs
{
    /// <summary>Generated wire format for [Job] "charge-card".</summary>
    internal static class ChargeCardWire
    {
        public static byte[] Serialize(global::Acme.Jobs.ChargeCard value)
        {
            var buffer = new global::System.IO.MemoryStream();
            using (var writer = new global::System.Text.Json.Utf8JsonWriter(buffer))
            {
                writer.WriteStartObject();
                if (value.OrderId is null)
                {
                    writer.WriteNull("OrderId");
                }
                else
                {
                    writer.WriteString("OrderId", value.OrderId);
                }
                writer.WriteNumber("Amount", value.Amount);
                if (value.CorrelationId.HasValue)
                {
                    writer.WriteString("CorrelationId", value.CorrelationId.Value);
                }
                else
                {
                    writer.WriteNull("CorrelationId");
                }
                if (value.Region is null)
                {
                    writer.WriteNull("Region");
                }
                else
                {
                    writer.WriteString("Region", value.Region);
                }
                writer.WriteBoolean("Expedited", value.Expedited);
                writer.WriteEndObject();
            }
            return buffer.ToArray();
        }

        public static global::Acme.Jobs.ChargeCard Deserialize(global::System.ReadOnlyMemory<byte> payload)
        {
            var reader = new global::System.Text.Json.Utf8JsonReader(payload.Span);
            string? __orderId = null;
            int __amount = default;
            global::System.Guid? __correlationId = null;
            string? __region = "eu";
            bool __expedited = default;

            if (!reader.Read() || reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)
            {
                throw new global::System.Text.Json.JsonException("Expected a JSON object.");
            }
            while (reader.Read() && reader.TokenType == global::System.Text.Json.JsonTokenType.PropertyName)
            {
                if (reader.ValueTextEquals("OrderId"))
                {
                    reader.Read();
                    __orderId = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : reader.GetString();
                }
                else if (reader.ValueTextEquals("Amount"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __amount = reader.GetInt32();
                    }
                }
                else if (reader.ValueTextEquals("CorrelationId"))
                {
                    reader.Read();
                    __correlationId = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : reader.GetGuid();
                }
                else if (reader.ValueTextEquals("Region"))
                {
                    reader.Read();
                    __region = reader.TokenType == global::System.Text.Json.JsonTokenType.Null ? null : reader.GetString();
                }
                else if (reader.ValueTextEquals("Expedited"))
                {
                    reader.Read();
                    if (reader.TokenType != global::System.Text.Json.JsonTokenType.Null)
                    {
                        __expedited = reader.GetBoolean();
                    }
                }
                else
                {
                    reader.Read();
                    reader.Skip();
                }
            }
            return new global::Acme.Jobs.ChargeCard(__orderId!, __amount, __correlationId, __region!) { Expedited = __expedited };
        }
    }
}
