using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using BackWave.Storage;

namespace BackWave.Jobs;

/// <summary>
/// One job type's entry in the Job Registry: its Wire Name, its serialization, and how to execute it
/// against a handler resolved from dependency injection.
/// </summary>
/// <remarks>
/// <para>
/// The source generator emits this same shape, but not this same serialization. A generated
/// registration serializes through a per-job-type <c>Utf8JsonWriter</c> codec the generator also
/// emits. <see cref="Create{TJob,THandler}"/> serializes through the
/// <see cref="JsonTypeInfo{T}"/> the caller passes. The two encodings are not interchangeable: the
/// generated codec writes an enum as its string name and tolerates a JSON null for a non-nullable
/// member, and System.Text.Json writes an enum as a number by default and applies the naming policy of
/// the caller's context. Moving a live job type from one path to the other rewrites its wire format.
/// </para>
/// <para>
/// A host contributes a hand-built registration by registering it in the container:
/// <c>services.AddSingleton(JobRegistration.Create&lt;TJob, THandler&gt;(...))</c>. <c>AddBackWave</c>
/// folds every contributed registration into the registry that <c>UseRegistry(...)</c> supplied, so a
/// type that generated serialization cannot express lives alongside the generated ones.
/// </para>
/// </remarks>
public sealed class JobRegistration
{
    /// <summary>The stable Wire Name identifying this job type on the wire and in storage.</summary>
    public required string WireName { get; init; }

    /// <summary>The CLR payload type this registration serializes and dispatches.</summary>
    public required Type JobType { get; init; }

    /// <summary>The Queue jobs of this type go to unless overridden at enqueue time.</summary>
    public required string Queue { get; init; }

    /// <summary>
    /// The Tags every job of this type starts with — additive only: unioned into the caller's
    /// per-enqueue Tags, never subtracted. Built from the <c>[Job]</c> attribute's Labels, so these
    /// are always Labels. Defaults to <see cref="JobTags.Empty"/>.
    /// </summary>
    public JobTags DefaultTags { get; init; } = JobTags.Empty;

    /// <summary>Deserializes a stored payload blob into the strongly typed job payload.</summary>
    public required Func<ReadOnlyMemory<byte>, object> Deserialize { get; init; }

    /// <summary>Serializes a job payload to the bytes the store persists.</summary>
    public required Func<object, byte[]> Serialize { get; init; }

    /// <summary>Resolves the handler from the service provider and runs one Attempt.</summary>
    public required Func<IServiceProvider, object, JobContext, CancellationToken, Task> Execute { get; init; }

    /// <summary>
    /// The serialization metadata for this job type's <b>Job Output</b> value, when the type declares one
    /// - the typed Job Output codec used to read or write the job's output without the caller passing a
    /// serializer. Held as the non-generic base so a registration can carry any output shape; a typed
    /// reader casts it back to the declared output type. Null for a job type that emits no typed output.
    /// </summary>
    public JsonTypeInfo? OutputTypeInfo { get; init; }

    /// <summary>
    /// The per-job-type retry override this type declares with <c>[Retry(...)]</c>, as pure data (ADR
    /// 0051). The loud-failure path resolves it in place of the Worker Group policy. Null when the type
    /// carries no <c>[Retry]</c>, so the job inherits the Worker Group policy.
    /// </summary>
    public Core.RetryDisposition? Retry { get; init; }

    /// <summary>
    /// Builds a registration from a caller-supplied <see cref="JsonTypeInfo{T}"/> (source-generated by
    /// the application), keeping the path reflection-free and NativeAOT-safe.
    /// </summary>
    /// <typeparam name="TJob">The job payload type.</typeparam>
    /// <typeparam name="THandler">The handler that processes <typeparamref name="TJob"/>.</typeparam>
    /// <param name="wireName">The stable Wire Name for this job type.</param>
    /// <param name="typeInfo">
    /// The source-generated serialization metadata for <typeparamref name="TJob"/>.
    /// </param>
    /// <param name="queue">The Queue jobs of this type go to unless overridden at enqueue time.</param>
    /// <param name="labels">
    /// Optional default Tag Labels every job of this type starts with; null or empty means none.
    /// </param>
    /// <param name="outputTypeInfo">
    /// Optional source-generated metadata for the type's <b>Job Output</b> value, when it declares one -
    /// supply the metadata for the exact output type so the typed Job Output codec can read or write the
    /// job's output with no caller-passed serializer. Null when the type emits no typed output.
    /// </param>
    /// <param name="retry">
    /// The per-job-type <c>[Retry(...)]</c> override as data, or null to inherit the Worker Group policy
    /// (ADR 0051). Build it with <see cref="Core.RetryDisposition.FromIntervals"/>, which validates the
    /// ceiling and the intervals.
    /// </param>
    /// <returns>A registration ready to add to a <see cref="JobRegistry"/>.</returns>
    public static JobRegistration Create<TJob, THandler>(
        string wireName,
        JsonTypeInfo<TJob> typeInfo,
        string queue = "default",
        string[]? labels = null,
        JsonTypeInfo? outputTypeInfo = null,
        Core.RetryDisposition? retry = null)
        where THandler : IJobHandler<TJob>
        => new()
        {
            WireName = wireName,
            JobType = typeof(TJob),
            Queue = queue,
            OutputTypeInfo = outputTypeInfo,
            Retry = retry,
            DefaultTags = labels is null or { Length: 0 }
                ? JobTags.Empty
                : JobTags.From(Array.ConvertAll(labels, JobTag.Label)),
            Deserialize = payload => JsonSerializer.Deserialize(payload.Span, typeInfo)
                ?? throw new InvalidOperationException($"Payload for wire name '{wireName}' deserialized to null."),
            Serialize = job => JsonSerializer.SerializeToUtf8Bytes((TJob)job, typeInfo),
            Execute = (services, job, context, cancellationToken) =>
            {
                var handler = (IJobHandler<TJob>?)services.GetService(typeof(IJobHandler<TJob>))
                    ?? throw new InvalidOperationException(
                        $"No IJobHandler<{typeof(TJob).Name}> is registered for wire name '{wireName}'.");
                return handler.HandleAsync((TJob)job, context, cancellationToken);
            },
        };
}
